### ISSUE TITLE
[bug]Extra experience drop

### ISSUE THREAD

**Issue by MoeShimaKaze** [JeannotM/DynamicDifficulty#13]
When I set the 'keep-inventory' option to true, the player's inventory and experience are saved normally, but experience orbs are left at the death point, which can lead to players infinitely farming experience. Please fix.

**Comment by WilliDieEnte** [comment]
#3 I guess

**Comment by MoeShimaKaze** [comment]
> #3 I guess

yes，it is a same problem but not be fixed in the latest version

**Comment by JeannotM** [comment]
Yeah, I am still a bit busy with school and another project, But I think I'll upload everything once 1.20 releases. If you want it earlier you can contact me on Discord Jeans#9421 (might change soon due to Discord) or join the server here: https://discord.gg/eYDRtWV5kj and DM me 

For now I'll be closing this comment since it was already fixed on Discord. Have a nice day!
